services:
  openttd:
    container_name: openttd
    image: burrowops/openttd:latest
    restart: unless-stopped
    volumes:
      - ./openttd:/config
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    # Uncomment to control save loading behavior
    #environment:
    #  - "loadgame=last-autosave"
    #  - "savepath=/home/openttd/.openttd/save"
