name: Verify Docker image

on:
  pull_request:
    paths:
      - "docker/**"
      - ".github/workflows/docker-build-pr.yml"

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: docker
          file: docker/dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
